name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "014db4d35d6677a17f94f8a51a036622"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.rusin.dpdns.org", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "af047c6ce2c04feebd906a86399ca59c" },
  { binding = "PBIMGS", id ="bf59b59998de4f56a1234038b91f3c7a" }
]

[site]
bucket = "./static/dist"
